INPUT_READ_BARCODE = "INPUT_READ_BARCODE"
OUTPUT_READ_BARCODE = "OUTPUT_READ_BARCODE"
DONE_RETRIEVE_DATA = "DONE_RETRIEVE_DATA"
CAMERA_READER_QUEUE = "CAMERA_READER_QUEUE"
IMAGE = "IMAGE"
BARCODE = "BARCODE"
DATA = "DATA"


MAX_Q_SIZE = "MAX_Q_SIZE"
LOG_FILE = "LOG_FILE"
TIMEOUT = "TIMEOUT"
